-- =========================================================
-- BANCO DE PREGUNTAS EXTENDIDO: GDPR / LEY DE DATOS
-- Total: 50 Preguntas para Diagnóstico Robusto
-- =========================================================

DELETE FROM public.diagnostic_questions WHERE framework = 'GDPR';

INSERT INTO public.diagnostic_questions (framework, pillar, code, title, options) VALUES
-- PILLAR: Consentimiento y Base Legal (10 preguntas)
('GDPR', 'Consentimiento y Base Legal', 'gdpr_01', '¿Existe un mecanismo claro, positivo e inequívoco (sin casillas premarcadas) para recolectar el consentimiento?', '[{"text": "No o usamos casillas premarcadas", "score": 1}, {"text": "Solo en algunos formularios", "score": 3}, {"text": "Sí, en todos los puntos de captura", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_02', '¿Los usuarios pueden retirar su consentimiento con la misma facilidad con la que lo dieron (ej. con un clic)?', '[{"text": "No, deben contactar a soporte", "score": 1}, {"text": "Proceso manual pero documentado", "score": 3}, {"text": "Sí, automatizado y de un clic", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_03', '¿Se mantiene un registro inmutable y auditable de cuándo y cómo se obtuvo el consentimiento de cada usuario?', '[{"text": "No se registra", "score": 1}, {"text": "Registros dispersos en logs", "score": 3}, {"text": "Registro centralizado y auditable", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_04', '¿El consentimiento para el uso de cookies y rastreadores es explícito y granular (separado por analítica, marketing, etc.)?', '[{"text": "Aceptación implícita/global", "score": 1}, {"text": "Aviso sin granularidad", "score": 3}, {"text": "Banner granular y bloqueante", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_05', '¿Se re-solicita el consentimiento cuando cambian sustancialmente las finalidades del tratamiento de los datos?', '[{"text": "Nunca", "score": 1}, {"text": "Se envía aviso pero no se re-pide", "score": 3}, {"text": "Sí, es obligatorio", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_06', '¿Se requiere y verifica el consentimiento parental para el tratamiento de datos de menores de edad?', '[{"text": "No aplican controles", "score": 1}, {"text": "Aviso genérico para menores", "score": 3}, {"text": "Verificación estricta implementada", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_07', '¿Se documenta formalmente la base de legitimación (consentimiento, contrato, interés legítimo) para cada actividad?', '[{"text": "No se documenta", "score": 1}, {"text": "Solo en los avisos de privacidad", "score": 3}, {"text": "Mapeado en el RoPA", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_08', '¿Se realiza y documenta la "Prueba de Sopesación" (LIA) antes de basarse en el "Interés Legítimo"?', '[{"text": "No sabemos qué es LIA", "score": 1}, {"text": "Evaluación informal", "score": 3}, {"text": "DPIA/LIA formal documentado", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_09', '¿Las políticas de privacidad están redactadas en lenguaje claro, sencillo y sin jerga legal compleja?', '[{"text": "Texto legal incomprensible", "score": 1}, {"text": "Mejorado pero denso", "score": 3}, {"text": "Lenguaje claro y en capas", "score": 5}]'),
('GDPR', 'Consentimiento y Base Legal', 'gdpr_10', '¿Existen mecanismos para prohibir que la provisión de un servicio esté condicionada a consentir el uso de datos innecesarios?', '[{"text": "Se fuerza el consentimiento", "score": 1}, {"text": "Práctica mixta", "score": 3}, {"text": "Estricta separación de servicios", "score": 5}]'),

-- PILLAR: Derechos de los Interesados (ARCO/GDPR) (10 preguntas)
('GDPR', 'Derechos de los Interesados', 'gdpr_11', '¿Existe un proceso estandarizado para atender las Solicitudes de Acceso a Datos (DSAR) dentro de los plazos legales (30 días)?', '[{"text": "No definido", "score": 1}, {"text": "Proceso manual y ad-hoc", "score": 3}, {"text": "Proceso formalizado con SLAs", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_12', '¿El sistema permite a los usuarios exportar su información en un formato estructurado y legible por máquina (Portabilidad)?', '[{"text": "Imposible", "score": 1}, {"text": "Se envía en PDF", "score": 3}, {"text": "Exportación directa en JSON/CSV", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_13', '¿Están mapeados todos los repositorios para garantizar el borrado efectivo ante solicitudes de Derecho al Olvido?', '[{"text": "No conocemos dónde están todos", "score": 1}, {"text": "Solo en base principal", "score": 3}, {"text": "Mapeo completo (incluso terceros)", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_14', '¿El proceso de Derecho al Olvido contempla y ejecuta la eliminación técnica también en los respaldos (Backups)?', '[{"text": "No se borran backups", "score": 1}, {"text": "Se borran tras expirar el backup", "score": 3}, {"text": "Herramientas de expurgo activas", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_15', '¿Tienen un canal de comunicación directo y gratuito para que los usuarios ejerzan sus derechos de privacidad?', '[{"text": "Deben enviar carta física", "score": 1}, {"text": "Email genérico", "score": 3}, {"text": "Portal/Formulario específico", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_16', '¿Se notifica automáticamente a terceros (procesadores) cuando un usuario solicita la rectificación o borrado de sus datos?', '[{"text": "No se avisa a terceros", "score": 1}, {"text": "Proceso manual periódico", "score": 3}, {"text": "Notificación automatizada por API", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_17', '¿Los usuarios tienen la posibilidad de restringir el tratamiento de sus datos mientras se resuelve una disputa legal?', '[{"text": "Funcionalidad inexistente", "score": 1}, {"text": "Se bloquea la cuenta entera", "score": 3}, {"text": "Bloqueo granular de tratamiento", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_18', '¿El sistema permite al usuario oponerse al procesamiento de datos para fines de marketing directo de forma inmediata?', '[{"text": "Difícil de gestionar", "score": 1}, {"text": "Toma días reflejarse", "score": 3}, {"text": "Baja (Opt-out) en tiempo real", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_19', '¿Existe un protocolo para evitar la "Toma de Decisiones Individuales Automatizadas" sin revisión humana si afectan legalmente al usuario?', '[{"text": "Decisiones 100% algorítmicas", "score": 1}, {"text": "Revisión bajo demanda", "score": 3}, {"text": "Intervención humana garantizada", "score": 5}]'),
('GDPR', 'Derechos de los Interesados', 'gdpr_20', '¿Se validan y autentican de forma segura las identidades de quienes ejercen los derechos ARCO para evitar fraude?', '[{"text": "Solo se pide el email", "score": 1}, {"text": "Se pide copia de ID sin cifrar", "score": 3}, {"text": "Autenticación segura/MFA", "score": 5}]'),

-- PILLAR: Privacidad desde el Diseño y Retención (10 preguntas)
('GDPR', 'Privacidad y Retención', 'gdpr_21', '¿Se realiza una Evaluación de Impacto de Protección de Datos (DPIA) antes de implementar nuevos sistemas o cambios de negocio?', '[{"text": "Nunca", "score": 1}, {"text": "Para proyectos muy críticos", "score": 3}, {"text": "Obligatorio y estandarizado", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_22', '¿Los sistemas aplican la máxima configuración de privacidad por defecto (Privacy by Default) para usuarios nuevos?', '[{"text": "Todo público por defecto", "score": 1}, {"text": "Configuración intermedia", "score": 3}, {"text": "Privacidad máxima por defecto", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_23', '¿Se aplican técnicas de minimización de datos para recolectar exclusivamente los datos indispensables para el servicio?', '[{"text": "Se recolecta por si acaso", "score": 1}, {"text": "Intentamos minimizar", "score": 3}, {"text": "Auditorías de minimización", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_24', '¿Están definidos, documentados y automatizados los tiempos de retención de datos según la base legal?', '[{"text": "Se guardan para siempre", "score": 1}, {"text": "Definidos pero borrado manual", "score": 3}, {"text": "Políticas de borrado automático", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_25', '¿Los datos personales en entornos que no son de producción (Dev/QA) están enmascarados o anonimizados sistemáticamente?', '[{"text": "Usamos datos productivos reales", "score": 1}, {"text": "Enmascaramiento manual ad-hoc", "score": 3}, {"text": "Anonimización automática", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_26', '¿Se documentan los diagramas de flujo de datos y arquitectura con una perspectiva de privacidad antes del desarrollo?', '[{"text": "No hay diagramas", "score": 1}, {"text": "Solo de arquitectura general", "score": 3}, {"text": "Incluyen controles de privacidad", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_27', '¿Seudoanonimizan o cifran los datos personales de alto riesgo desde el momento de la ingesta?', '[{"text": "Se almacenan en texto claro", "score": 1}, {"text": "Solo algunos campos críticos", "score": 3}, {"text": "Cifrado sistemático", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_28', '¿Existe una política para destruir de forma irrecuperable los discos y soportes físicos que contuvieron datos sensibles?', '[{"text": "Se tiran a la basura", "score": 1}, {"text": "Se reformatean", "score": 3}, {"text": "Wipe certificado / Destrucción", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_29', '¿Las bases de datos históricas sufren procesos de anonimización irreversible para poder ser usadas en analítica?', '[{"text": "Se analizan con PII", "score": 1}, {"text": "Se quitan nombres solamente", "score": 3}, {"text": "Anonimización criptográfica", "score": 5}]'),
('GDPR', 'Privacidad y Retención', 'gdpr_30', '¿El equipo de desarrollo recibe capacitaciones anuales obligatorias sobre prácticas de desarrollo seguro y Privacy by Design?', '[{"text": "Nunca", "score": 1}, {"text": "Ocasionalmente", "score": 3}, {"text": "Capacitación formal certificada", "score": 5}]'),

-- PILLAR: Gobernanza, Accountability y DPO (10 preguntas)
('GDPR', 'Gobernanza y DPO', 'gdpr_31', '¿La organización ha designado formalmente un Delegado de Protección de Datos (DPO) que reporte a la alta dirección?', '[{"text": "No", "score": 1}, {"text": "Responsabilidad compartida de TI", "score": 3}, {"text": "DPO dedicado e independiente", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_32', '¿Se mantiene y actualiza activamente un Registro de Actividades de Tratamiento (RoPA) según el Artículo 30?', '[{"text": "No tenemos", "score": 1}, {"text": "Documento estático obsoleto", "score": 3}, {"text": "Catálogo dinámico auditado", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_33', '¿La alta dirección (Directorio / C-Level) recibe reportes regulares sobre el estado de cumplimiento normativo y riesgos de privacidad?', '[{"text": "Nunca", "score": 1}, {"text": "Solo si hay incidentes", "score": 3}, {"text": "Métricas reportadas regularmente", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_34', '¿Los empleados con acceso a datos sensibles firman acuerdos de confidencialidad (NDA) explícitos en su contratación?', '[{"text": "No", "score": 1}, {"text": "Cláusulas estándar débiles", "score": 3}, {"text": "NDAs estrictos y revisados", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_35', '¿El DPO o responsable de privacidad es involucrado obligatoriamente en la aprobación de nuevos proveedores tecnológicos?', '[{"text": "No", "score": 1}, {"text": "Solo se le avisa después", "score": 3}, {"text": "Aprobación obligatoria (Gatekeeper)", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_36', '¿Existen políticas disciplinarias claras y comunicadas en caso de que un empleado vulnere las normas de privacidad?', '[{"text": "No existen", "score": 1}, {"text": "Informales", "score": 3}, {"text": "Políticas formales ejecutables", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_37', '¿Se realizan auditorías internas periódicas de cumplimiento GDPR de manera cruzada o independiente?', '[{"text": "Nunca", "score": 1}, {"text": "Auto-evaluación del propio equipo", "score": 3}, {"text": "Auditoría interna/externa", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_38', '¿Existe un presupuesto asignado específicamente a iniciativas, herramientas y cumplimiento de privacidad de datos?', '[{"text": "Ninguno", "score": 1}, {"text": "Presupuesto compartido en TI", "score": 3}, {"text": "Línea presupuestal específica", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_39', '¿Las brechas normativas identificadas en los DPIA son rastreadas mediante un plan de remediación corporativo formal?', '[{"text": "No se rastrean", "score": 1}, {"text": "Seguimiento por correo", "score": 3}, {"text": "Gestor de tareas/riesgos formal", "score": 5}]'),
('GDPR', 'Gobernanza y DPO', 'gdpr_40', '¿La organización está suscrita y monitorea alertas legales para adaptarse ágilmente a cambios regulatorios y multas recientes?', '[{"text": "No hay monitoreo", "score": 1}, {"text": "Depende de asesores externos", "score": 3}, {"text": "Vigilancia normativa activa", "score": 5}]'),

-- PILLAR: Seguridad, Brechas y Terceros (10 preguntas)
('GDPR', 'Seguridad y Terceros', 'gdpr_41', '¿Los datos en tránsito (redes) y en reposo (discos/BD) están protegidos con algoritmos de cifrado fuertes y actualizados?', '[{"text": "No", "score": 1}, {"text": "Solo en algunas bases", "score": 3}, {"text": "Cifrado sistemático y auditable", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_42', '¿Se ha implementado Control de Acceso Basado en Roles (RBAC) asegurando el Principio de Menor Privilegio?', '[{"text": "Todos tienen acceso total", "score": 1}, {"text": "Roles muy genéricos", "score": 3}, {"text": "Menor privilegio garantizado", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_43', '¿El proceso de respuesta a incidentes (Incident Response) asegura la notificación a la Autoridad de Control en menos de 72h tras una brecha?', '[{"text": "No hay proceso", "score": 1}, {"text": "Proceso lento, supera las 72h", "score": 3}, {"text": "Simulacros exitosos < 72h", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_44', '¿Se notifica de forma directa y oportuna a los usuarios afectados si la brecha de datos representa un alto riesgo para sus derechos?', '[{"text": "Se intenta ocultar", "score": 1}, {"text": "Avisos públicos genéricos", "score": 3}, {"text": "Notificación directa definida", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_45', '¿Se auditan periódicamente los logs de acceso a bases de datos con PII para detectar accesos inusuales o internos maliciosos?', '[{"text": "No hay logs de PII", "score": 1}, {"text": "Existen logs pero no se revisan", "score": 3}, {"text": "Monitoreo SIEM / Alertas", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_46', '¿Se firman Acuerdos de Procesamiento de Datos (DPA) con todos los proveedores tecnológicos que actúan como "Encargados"?', '[{"text": "Se usan contratos estándar", "score": 1}, {"text": "Solo con proveedores Cloud", "score": 3}, {"text": "DPA firmado con cada Encargado", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_47', '¿Se auditan y verifican las prácticas de seguridad de los proveedores tecnológicos (Vendor Risk Assessment) antes de contratarlos?', '[{"text": "Nunca", "score": 1}, {"text": "Cuestionario Excel simple", "score": 3}, {"text": "Auditoría formal obligatoria", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_48', '¿Existe un mapeo formal de las Transferencias Internacionales de Datos y sus garantías legales (SCC, Normas Corporativas Vinculantes)?', '[{"text": "No sabemos a dónde viajan", "score": 1}, {"text": "Mapeo parcial de nubes", "score": 3}, {"text": "Registro estricto de TIDs", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_49', '¿La plataforma exige la autenticación de múltiples factores (MFA) para cualquier empleado que acceda a información personal sensible?', '[{"text": "Solo contraseñas simples", "score": 1}, {"text": "Solo para administradores", "score": 3}, {"text": "MFA obligatorio para todos", "score": 5}]'),
('GDPR', 'Seguridad y Terceros', 'gdpr_50', '¿Se realizan pruebas de penetración (Pen Testing) anuales enfocadas en la seguridad de los repositorios de datos personales?', '[{"text": "Nunca", "score": 1}, {"text": "Solo escaneos automáticos", "score": 3}, {"text": "Pen Testing manual y periódico", "score": 5}]');
